// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBL8JOvxjQ9lUAkUFFlMthldlsvKa3oNME',
    appId: '1:94003824961:web:1da618cae4c472274739c0',
    messagingSenderId: '94003824961',
    projectId: 'bongbieng-app',
    authDomain: 'bongbieng-app.firebaseapp.com',
    storageBucket: 'bongbieng-app.firebasestorage.app',
    measurementId: 'G-N5RCW4YNTE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCenpKOMOjIpYRhYuMwKpw8ZJrPvrAsC4I',
    appId: '1:94003824961:android:0c5fc8477b5706804739c0',
    messagingSenderId: '94003824961',
    projectId: 'bongbieng-app',
    storageBucket: 'bongbieng-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCpDLxrWE4GRoc38j9a_enUH7dMU5w-To',
    appId: '1:94003824961:ios:d5a983cf371df91a4739c0',
    messagingSenderId: '94003824961',
    projectId: 'bongbieng-app',
    storageBucket: 'bongbieng-app.firebasestorage.app',
    iosBundleId: 'com.example.bongbiengApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCpDLxrWE4GRoc38j9a_enUH7dMU5w-To',
    appId: '1:94003824961:ios:d5a983cf371df91a4739c0',
    messagingSenderId: '94003824961',
    projectId: 'bongbieng-app',
    storageBucket: 'bongbieng-app.firebasestorage.app',
    iosBundleId: 'com.example.bongbiengApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBL8JOvxjQ9lUAkUFFlMthldlsvKa3oNME',
    appId: '1:94003824961:web:77ded9030a673fd14739c0',
    messagingSenderId: '94003824961',
    projectId: 'bongbieng-app',
    authDomain: 'bongbieng-app.firebaseapp.com',
    storageBucket: 'bongbieng-app.firebasestorage.app',
    measurementId: 'G-XX5ERR8SS9',
  );

}